# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# Automatically convert third-party libraries to use AndroidX
android.useAndroidX=true

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and not the resources declared in its dependencies.
android.nonTransitiveRClass=true

# Kotlin code style
kotlin.code.style=official

# JVM arguments for the Gradle daemon
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
