package com.sih26168.deadreckoning

import com.sih26168.deadreckoning.engine.ExtendedKalmanFilter
import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Bit-exact parity test between ExtendedKalmanFilter.kt and Python's
 * VehicleEKF (phase10_fusion_engine.py), same convention as
 * PositionEstimatorTest.kt's Python<->Kotlin parity checks.
 *
 * Reference values generated by running the exact same input sequence
 * through VehicleEKF directly (see phase10_fusion_engine.py session notes).
 */
class ExtendedKalmanFilterTest {

    private val TOL = 1e-6

    private fun newEkf(): ExtendedKalmanFilter {
        val ekf = ExtendedKalmanFilter(
            initPos = doubleArrayOf(100.0, 200.0),
            initVel = doubleArrayOf(2.0, 3.0),
            initHeading = 0.5,
            sigmaAProc = 4.0,
            sigmaWProc = Math.toRadians(2.0),
            sigmaBaProc = 1e-3,
            sigmaBwProc = 1e-4
        )
        ekf.seedBias(5, 0.05)
        ekf.seedBias(6, -0.03)
        ekf.seedBias(7, 0.01)
        return ekf
    }

    private val inputs = listOf(
        doubleArrayOf(1.2, 0.3, 0.05, 0.1),
        doubleArrayOf(0.8, -0.1, 0.02, 0.1),
        doubleArrayOf(1.5, 0.2, -0.03, 0.1),
        doubleArrayOf(0.9, 0.0, 0.01, 0.1),
        doubleArrayOf(1.1, -0.2, 0.04, 0.1)
    )

    private fun assertState(x: DoubleArray, expected: DoubleArray, label: String) {
        for (i in 0 until 8) {
            assertEquals("$label state[$i]", expected[i], x[i], TOL)
        }
    }

    @Test
    fun predictSequence_matchesPython() {
        val ekf = newEkf()
        for (inp in inputs) ekf.predict(inp[0], inp[1], inp[2], inp[3])
        assertState(
            ekf.x,
            doubleArrayOf(101.04810255735578, 201.62443989666212, 2.2220832702638518, 3.4769899936702235, 0.504, 0.05, -0.03, 0.01),
            "After 5 predicts"
        )
    }

    @Test
    fun nhcUpdate_matchesPython() {
        val ekf = newEkf()
        for (inp in inputs) ekf.predict(inp[0], inp[1], inp[2], inp[3])
        ekf.updateNhc(rLat = 0.2)
        assertState(
            ekf.x,
            doubleArrayOf(100.99292107860282, 201.65499865646484, 2.0188630385623414, 3.5893180152014117, 0.5101900925802947, 0.04999798686386575, -0.031118407347994193, 0.009966700112674184),
            "After NHC"
        )
    }

    @Test
    fun headingUpdate_matchesPython() {
        val ekf = newEkf()
        for (inp in inputs) ekf.predict(inp[0], inp[1], inp[2], inp[3])
        ekf.updateNhc(rLat = 0.2)
        ekf.updateHeading(0.55, rHeading = Math.toRadians(8.0))
        assertState(
            ekf.x,
            doubleArrayOf(101.00293357616874, 201.6496917187192, 2.0559594194660917, 3.5692875644902564, 0.5207661050545762, 0.049998300174201225, -0.030944346301930718, 0.009914785071689466),
            "After heading update"
        )
    }

    @Test
    fun zuptUpdate_matchesPython() {
        val ekf = newEkf()
        for (inp in inputs) ekf.predict(inp[0], inp[1], inp[2], inp[3])
        ekf.updateNhc(rLat = 0.2)
        ekf.updateHeading(0.55, rHeading = Math.toRadians(8.0))
        ekf.updateZupt(rZupt = 0.05)
        assertState(
            ekf.x,
            doubleArrayOf(100.44669324319638, 200.68303069321055, 0.006021307948003596, 0.00782288787831531, 0.5077058401236849, 0.06951379815871284, -0.03130385324773107, 0.00997281815551788),
            "After ZUPT"
        )
    }

    @Test
    fun mlSpeedUpdate_matchesPython() {
        val ekf = newEkf()
        for (inp in inputs) ekf.predict(inp[0], inp[1], inp[2], inp[3])
        ekf.updateNhc(rLat = 0.2)
        ekf.updateMlSpeed(2.5, rSpeed = 1.8)
        assertState(
            ekf.x,
            doubleArrayOf(100.9407290849787, 201.56082168552305, 1.826537312156562, 3.2422933573754547, 0.5100063853277672, 0.05188276905012206, -0.031125248826226, 0.009967039260600922),
            "After ML speed update"
        )
    }

    @Test
    fun gnssUpdate_matchesPython() {
        val ekf = ExtendedKalmanFilter(
            initPos = doubleArrayOf(0.0, 0.0),
            initVel = doubleArrayOf(1.0, 1.0),
            initHeading = 0.2,
            sigmaAProc = 4.0,
            sigmaWProc = Math.toRadians(2.0),
            sigmaBaProc = 1e-3,
            sigmaBwProc = 1e-4
        )
        ekf.predict(1.0, 0.5, 0.02, 0.1)
        ekf.updateGnss(doubleArrayOf(5.0, 6.0), doubleArrayOf(1.5, 1.2), rPos = 3.0, rVel = 0.3)
        assertState(
            ekf.x,
            doubleArrayOf(3.7096214448416465, 4.4409580123317545, 1.4054373681573846, 1.1842168306030538, 0.20291041017993194, -0.00039052681555045484, 0.0010002167201432024, 0.0),
            "After GNSS update"
        )
    }
}
